-- ISO process-group / HLS / audit KPI seed
-- Source: data/ISO_심사체크포인트_DB시드_프로세스그룹.xlsx
-- Safe: does NOT DROP/TRUNCATE ESG kpi_master, companies, CBs, iso_clauses_master
-- KPI HLS normalize: 8.2~8.10 → 8.6~8.10
-- Prefer: python scripts/seed_process_group_masters.py
SET NAMES utf8mb4;
START TRANSACTION;
-- Clear only process-group seed tables (child → parent)
DELETE FROM `audit_kpi_master`;
DELETE FROM `standard_clause_map`;
DELETE FROM `standard_process_clause_map`;
DELETE FROM `process_group_hls_map`;
DELETE FROM `hls_master`;
DELETE FROM `standard_master`;
DELETE FROM `process_group_master`;
-- PROCESS_GROUP_MASTER
INSERT INTO process_group_master (process_group_id, process_group_name, hls_scope_desc) VALUES ('PG1', '경영·리더십 프로세스', 'HLS 4장, 5장');
INSERT INTO process_group_master (process_group_id, process_group_name, hls_scope_desc) VALUES ('PG2', '기획·리스크관리 프로세스', 'HLS 6장');
INSERT INTO process_group_master (process_group_id, process_group_name, hls_scope_desc) VALUES ('PG3', '인적자원·교육 프로세스', 'HLS 7.2 / 7.3 / 7.4');
INSERT INTO process_group_master (process_group_id, process_group_name, hls_scope_desc) VALUES ('PG4', '인프라·자산관리 프로세스', 'HLS 7.1 / 7.5');
INSERT INTO process_group_master (process_group_id, process_group_name, hls_scope_desc) VALUES ('PG5', '영업·수주·계약 프로세스', 'HLS 8장 운영 전반(도입부)');
INSERT INTO process_group_master (process_group_id, process_group_name, hls_scope_desc) VALUES ('PG6', '설계·개발·생산(운영) 프로세스', 'HLS 8장 핵심 실행');
INSERT INTO process_group_master (process_group_id, process_group_name, hls_scope_desc) VALUES ('PG7', '협력사·공급망관리 프로세스', 'HLS 8.4 외주/구매');
INSERT INTO process_group_master (process_group_id, process_group_name, hls_scope_desc) VALUES ('PG8', '성과평가·지속적개선 프로세스', 'HLS 9장, 10장');
-- STANDARD_MASTER
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO9001', 'ISO 9001:2015 (품질경영시스템)', 'Y', NULL);
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO14001', 'ISO 14001:2015/2026 (환경경영시스템)', 'Y', NULL);
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO45001', 'ISO 45001:2018 (안전보건경영시스템)', 'Y', NULL);
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO50001', 'ISO 50001:2018 (에너지경영시스템)', 'Y', '6.3~6.6 에너지 전용 하위조항 보유');
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO22000', 'ISO 22000:2018 (식품안전경영시스템)', 'Y', NULL);
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO27001', 'ISO/IEC 27001:2022 (정보보안경영시스템)', 'Y', '10.1=지속적개선, 10.2=부적합·시정조치(9001과 순서 반대)');
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO37001', 'ISO 37001:2016 (부패방지경영시스템)', 'Y', '8장이 8.1~8.10으로 세분화(운영통제 핵심)');
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO37301', 'ISO 37301:2021 (준법경영시스템)', 'Y', '10.1=지속적개선, 10.2=부적합·시정조치(9001과 순서 반대)');
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO22301', 'ISO 22301:2019 (사업연속성경영시스템)', 'Y', '8.2~8.6 BCM 전용 하위조항 보유, 10.1=지속적개선');
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO42001', 'ISO/IEC 42001:2023 (AI경영시스템)', 'Y', '6.1.2~6.1.4(계획), 8.2~8.4(실행) AI리스크·영향평가 이원구조');
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO19443', 'ISO 19443:2018 (원자력 공급망 품질경영)', 'Y', 'ISO9001 기반 + 원자력 산업 추가요구(부속서 A)');
INSERT INTO standard_master (standard_code, standard_name, hls_adopted, native_structure_note) VALUES ('ISO27701', 'ISO/IEC 27701:2019 (개인정보보호경영시스템)', 'Y*', '27001의 확장(extension) 표준. 자체 Clause5(=27001 4~10 대응)/6(27002가이드)/7=Annex A(컨트롤러)/8=Annex B(프로세서) 구조');
-- HLS_MASTER
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('4.1', '내외부 이슈 목록 작성(SWOT/PESTLE) / 이슈 모니터링 주기·책임자 지정 / 경영전략 연계 여부');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('4.2', '이해관계자 식별·요구사항 목록화 / 준수의무 결정 / 주기적 검토·갱신');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('4.3', '적용범위 문서화 / 경계·적용성 결정 근거 / 제외사항의 정당성');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('4.4', '프로세스 정의(입력·출력·상호작용) / 프로세스별 기준·방법·책임 / 유지·개선 체계');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('5.1', '최고경영자 인터뷰(방침-전략 정렬) / 자원제공 및 책무 / 프로세스접근·리스크사고 촉진');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('5.2', '방침 수립·문서화 / 조직 내 의사소통 / 이해관계자 이용가능성');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('5.3', '조직도 및 R&R 문서화 / 성과보고 책임자 지정 / 책임·권한 전달');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('6.1', '리스크·기회 결정 방법론 / 조치계획 수립·통합 / 효과성 평가');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('6.2', '측정가능한 목표 수립 / 달성계획(담당·일정·자원) / 목표 모니터링');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('6.3', '시스템 변경의 계획적 수행 / 자원·책임·권한 재배정 (표준별 조항 위치 상이 — CLAUSE_MAP 참조)');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('7.1', '인력·인프라·업무환경 자원 결정·제공 / 자원 적정성 검토');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('7.2', '역량기준 정의 / 교육훈련 실시·효과성평가 / 적격성기록 유지');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('7.3', '방침·목표 인식 / 본인기여·부적합영향 인식');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('7.4', '내부·외부 소통계획 / 소통실적 기록');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('7.5', '요구문서 작성·식별·개정관리 / 배포·접근·보관·폐기 / 외부출처문서 관리');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('8.1', '운용기준 수립·프로세스관리 / 외주프로세스 관리 / 계획된 변경관리·의도치않은변경검토');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('8.2', '표준별 상이 — CLAUSE_MAP 참조 (기준수립→실행증거→기록→부적합처리)');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('8.3', '표준별 상이 — CLAUSE_MAP 참조');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('8.4', '표준별 상이 — CLAUSE_MAP 참조');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('8.5', '표준별 상이 — CLAUSE_MAP 참조');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('8.6~8.10', '37001/22000/22301 등 세부단계 다수 보유 표준 전용 — CLAUSE_MAP 참조');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('9.1', '모니터링 대상·방법·시기·주기 결정 / 결과분석·평가·기록 / 시스템효과성 평가');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('9.2', '심사프로그램 수립 / 심사원 적격성·독립성 / 결과보고 및 시정조치 연계');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('9.3', '입력사항 완전성 / 출력(결정사항) / 기록유지 및 후속조치 이행');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('10.1', '개선기회의 결정·실행 / 미래니즈 대응 개선 (표준별 10장 순서 상이 — CLAUSE_MAP 참조)');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('10.2', '부적합대응(시정·격리) / 원인분석 및 시정조치 / 시정조치 효과성 검토');
INSERT INTO hls_master (hls_code, checkpoints_summary) VALUES ('10.3', '시스템의 적절성·충족성·효과성 지속개선 / 경영검토 결과의 개선반영');
-- PROCESS_GROUP_HLS_MAP
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG1', '4.1');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG1', '4.2');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG1', '4.3');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG1', '4.4');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG1', '5.1');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG1', '5.2');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG1', '5.3');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG2', '6.1');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG2', '6.2');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG2', '6.3');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG3', '7.2');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG3', '7.3');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG3', '7.4');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG4', '7.1');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG4', '7.5');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG5', '8.1');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG8', '9.1');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG8', '9.2');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG8', '9.3');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG8', '10.1');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG8', '10.2');
INSERT INTO process_group_hls_map (process_group_id, hls_code) VALUES ('PG8', '10.3');
-- STANDARD_PROCESS_CLAUSE_MAP
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO9001', 'PG5', '8.2', '요구사항 검토(수주검토)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO9001', 'PG6', '8.3', '설계·개발', '입력·출력, 검토·검증·유효성확인이 되어있는지 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO9001', 'PG6', '8.5', '생산 및 서비스 제공', '식별·추적, 고객재산관리, 보존, 인도 후 활동까지 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO9001', 'PG6', '8.6', '출하 검증', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO9001', 'PG6', '8.7', '부적합 출력물 관리', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO9001', 'PG7', '8.4', '외부공급자 평가·관리', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO14001', 'PG6', '8.1/8.2', '운용관리(수명주기 관점) 및 비상사태 대비·대응', '설계·조달·폐기까지 전체 수명주기 관점과 비상사태 대비·대응을 확인하세요. (14001은 8.2가 따로 없고 8.1에 포함됩니다)');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO45001', 'PG6', '8.1.2/8.1.3', '위험 제거·감소, 변경관리', '위험을 없애거나 줄이는 순서(관리의 위계)와 변경관리를 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO45001', 'PG6', '8.2', '비상대비 및 대응', '45001은 8.2가 따로 없고 8.1에 포함됩니다.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO45001', 'PG7', '8.1.4', '조달·도급·계약자 관리', '협력업체·도급자에 대한 안전관리가 되는지 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO50001', 'PG6', '8.1/8.2', '핵심설비 운전기준 및 설계 시 에너지 고려', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO50001', 'PG7', '8.3', '에너지 조달기준', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22000', 'PG4', '8.2', '선행요건프로그램(PRP)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22000', 'PG6', '8.3', '추적성 시스템', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22000', 'PG6', '8.4', '비상대응(회수 포함)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22000', 'PG6', '8.5', '위해요소분석·HACCP 관리계획', '이 표준의 핵심 조항이니 가장 꼼꼼히 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22000', 'PG6', '8.6', 'PRP·HACCP 계획 정보 갱신', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22000', 'PG4', '8.7', '모니터링·측정장비 관리', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22000', 'PG8', '8.8', '검증', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22000', 'PG8', '8.9', '부적합 제품·공정 관리(리콜 포함)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO27001', 'PG2', '8.2', '정보보안 위험평가 실행', '정기적으로, 또는 변경이 있을 때 실제로 위험평가를 하는지 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO27001', 'PG2', '8.3', '정보보안 위험처리 실행', 'Annex A 통제가 실제로 이행된 증거를 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37001', 'PG7', '8.2', '실사(Due Diligence)', '거래처·협력사 대상 실사를 하는지 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37001', 'PG5', '8.3', '재무통제', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37001', 'PG7', '8.4', '비재무통제(구매·인사 등)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37001', 'PG7', '8.5', '피지배조직·비즈니스파트너 통제', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37001', 'PG7', '8.6', '부패방지 서약', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37001', 'PG5', '8.7', '선물·접대·기부 기준', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37001', 'PG8', '8.8', '통제 미흡 시 대응', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37001', 'PG1', '8.9', '우려 제기(신고채널)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37001', 'PG8', '8.10', '조사 및 처리', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37301', 'PG1', '8.1', '운영계획·관리(컴플라이언스 통제)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37301', 'PG1', '8.2', '통제·절차 수립', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37301', 'PG1', '8.3', '우려 제기(신고채널)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO37301', 'PG8', '8.4', '조사 프로세스', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22301', 'PG2', '8.2', '사업영향분석(BIA)·리스크평가', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22301', 'PG6', '8.3', '사업연속성 전략·솔루션', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22301', 'PG6', '8.4', '사업연속성 계획·절차', '비상 대응조직 구성도 함께 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22301', 'PG8', '8.5', '복구훈련(연습 프로그램)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO22301', 'PG8', '8.6', '문서·역량 평가', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO42001', 'PG2', '8.2', 'AI 위험평가 실행', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO42001', 'PG2', '8.3', 'AI 위험처리 실행', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO42001', 'PG2', '8.4', 'AI 시스템 영향평가 실행', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO19443', 'PG5', '8.2', '요구사항 검토(수주검토)', NULL);
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO19443', 'PG6', '8.3/8.5', '설계·개발, 생산 및 서비스 제공', '안전중요품목(ITNS)과 특별공정 관리가 함께 되는지 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO19443', 'PG7', '8.4', '외부공급자 평가·관리', '위조·의심품목(CFSI) 방지와 하도급 관리도 함께 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO27701', 'PG6', 'Annex A', 'PII 컨트롤러 의무', '동의·목적제한·정보주체 권리지원이 되는지 확인하세요.');
INSERT INTO standard_process_clause_map (standard_code, process_group_id, actual_clause_no, clause_topic, guide_note) VALUES ('ISO27701', 'PG7', 'Annex B', 'PII 프로세서 의무', '처리지시서와 재위탁(하위처리자) 관리를 확인하세요.');
-- STANDARD_CLAUSE_MAP
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO9001', '6.3', '6.3', 'DIRECT', NULL, NULL);
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO14001', '6.3', NULL, 'INTEGRATED', '8.1', '14001은 6.3이 따로 없습니다. 8.1에서 변경관리를 같이 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '6.3', NULL, 'INTEGRATED', '8.1', '45001은 6.3이 따로 없습니다. 8.1에서 변경관리를 같이 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO50001', '6.3', '6.3', 'RENUMBERED', NULL, '50001의 6.3은 번호만 같고 내용이 다릅니다. 변경기획이 아니라 \\'에너지검토\\'를 확인하세요. (6.4 EnPI, 6.5 에너지베이스라인, 6.6 에너지데이터 수집계획도 따로 있으니 같이 확인하세요)');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '6.3', '6.3', 'DIRECT', NULL, NULL);
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '6.3', '6.3', 'DIRECT', NULL, NULL);
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '6.3', '6.3', 'DIRECT', NULL, NULL);
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '6.3', '6.3', 'DIRECT', NULL, NULL);
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22301', '6.3', '6.3', 'DIRECT', NULL, NULL);
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '6.3', '6.3', 'DIRECT', NULL, NULL);
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '6.3', '6.3', 'DIRECT', NULL, NULL);
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27701', '6.3', '6.3', 'DIRECT', NULL, '27001과 똑같이 보면 됩니다.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO14001', '4.1', '4.1', 'ADDITIONAL', NULL, '기후변화 이슈를 포함해서 확인하세요. (2026판은 더 꼼꼼히 봐야 함)');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '4.1', '4.1', 'ADDITIONAL', NULL, '근로자·작업환경·노동관행 이슈도 포함해서 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO50001', '4.1', '4.1', 'ADDITIONAL', NULL, '에너지 사용·비용·수급·규제 관련 이슈도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '4.1', '4.1', 'ADDITIONAL', NULL, '식품사슬에서 이 조직의 위치와 원료·제품 특성도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '4.1', '4.1', 'ADDITIONAL', NULL, '정보자산과 위협환경도 함께 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27701', '4.1', '5.2.1', 'ADDITIONAL', NULL, '적용받는 개인정보 법규·규제를 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '4.1', '4.1/4.5', 'ADDITIONAL', NULL, '부패에 노출되기 쉬운 산업·지역·거래유형인지 확인하고, 4.5 부패리스크평가와 연결해서 보세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '4.1', '4.1/4.5/4.6', 'ADDITIONAL', NULL, '준법 의무 환경과 4.6 컴플라이언스 리스크평가를 연결해서 보세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22301', '4.1', '4.1', 'ADDITIONAL', NULL, '사업이 중단될 수 있는 원인도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '4.1', '4.1', 'ADDITIONAL', NULL, '조직이 AI를 개발/제공/사용 중 어디에 해당하는지, AI 규제 동향도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '4.1', '4.1', 'ADDITIONAL', NULL, '원자력 공급망에서 이 조직의 위치와 안전문화 요구를 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '4.2', '4.2', 'ADDITIONAL', NULL, '근로자와 근로자대표의 니즈가 꼭 포함됐는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '4.2', '4.2', 'ADDITIONAL', NULL, '규제기관·고객이 요구하는 식품안전 요건(법규·고객규격)을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '4.2', '4.2', 'ADDITIONAL', NULL, '법적·규제·계약상 정보보안 요구사항을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27701', '4.2', '5.2.1', 'ADDITIONAL', NULL, '정보주체·감독기관 등 개인정보 관련 이해관계자 요구를 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '4.2', '4.5', 'ADDITIONAL', NULL, '컴플라이언스 의무가 목록으로 정리·문서화되어 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '4.2', '4.2', 'ADDITIONAL', NULL, 'AI로 영향받을 수 있는 개인·사회 그룹도 고려했는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '4.2', '4.2', 'ADDITIONAL', NULL, '최종고객(원전사업자)과 인허가기관의 요구를 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO9001', '4.3', '4.3', 'ADDITIONAL', NULL, '적용 안 되는 조항이 있으면 그 이유(고객요구·적합성에 영향 없음)를 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '4.3', '4.3', 'ADDITIONAL', NULL, '다른 조직과 주고받는 인터페이스·의존관계도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27701', '4.3', '5.2.3', 'ADDITIONAL', NULL, 'PIMS 범위가 ISMS 범위와 맞는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22301', '4.3', '4.3', 'ADDITIONAL', NULL, '범위에 포함된 제품·서비스와 제외 사유를 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '4.3', '4.3', 'ADDITIONAL', NULL, '범위에 포함된 AI 시스템·서비스가 무엇인지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '4.4', '4.4', 'ADDITIONAL', NULL, '선행요건프로그램(PRP)이 시스템 안에 포함되어 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27701', '4.4', '5.2.4', 'ADDITIONAL', NULL, 'ISMS와 통합된 PIMS가 수립돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '4.4', '4.4', 'ADDITIONAL', NULL, 'AI 시스템 전체 수명주기가 프로세스에 반영됐는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '5.1', '5.1', 'ADDITIONAL', NULL, '안전보건 문화를 경영진이 직접 주도하고, 근로자를 보호·참여시키는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '5.1', '5.1', 'ADDITIONAL', NULL, '식품안전문화(가치 공유·교육·행동)가 실제로 조성돼 있는지 증거를 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '5.1', '5.1', 'ADDITIONAL', NULL, '최고경영진이 컴플라이언스 기능을 실제로 지원하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '5.1', '5.1.1~5.1.3', 'ADDITIONAL', NULL, '지배기구(이사회)와 최고경영자의 역할이 나뉘어 있는지, 준법문화·거버넌스를 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '5.1', '5.1', 'ADDITIONAL', NULL, '원자력 안전문화를 경영진이 만들고 퍼뜨리는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO14001', '5.2', '5.2', 'ADDITIONAL', NULL, '오염예방·준수의무 충족·지속개선 의지가 방침에 담겨 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '5.2', '5.2', 'ADDITIONAL', NULL, '안전한 작업조건 제공, 위험제거, 근로자 협의·참여 의지가 방침에 담겨 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO50001', '5.2', '5.2', 'ADDITIONAL', NULL, '에너지성과 개선과 자원 확보 의지가 방침에 담겨 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '5.2', '5.2', 'ADDITIONAL', NULL, '부패 금지, 신고 장려, 위반 시 제재가 방침에 명시돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '5.2', '5.2', 'ADDITIONAL', NULL, '준법 의무 충족 의지가 방침에 담겨 있고 지배기구 승인을 받았는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '5.2', '5.2', 'ADDITIONAL', NULL, 'AI 원칙(윤리·투명성 등)과 방침이 서로 맞는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '5.3', '5.3', 'ADDITIONAL', NULL, '식품안전팀과 팀장이 지정돼 있고 역량이 기록돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '5.3', '5.3', 'ADDITIONAL', NULL, '부패방지 컴플라이언스 기능이 독립적으로 권한을 갖고 지배기구에 직접 보고하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '5.3', '5.3.1~5.3.4', 'ADDITIONAL', NULL, '지배기구/컴플라이언스기능/관리자/일반직원의 책임이 각각 나뉘어 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '5.3', '5.3', 'ADDITIONAL', NULL, '모든 계층의 근로자에게 안전보건 책임이 부여돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '5.3', '5.3', 'ADDITIONAL', NULL, 'AI 리스크·영향평가를 누가 책임지는지 지정돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO14001', '6.1', '6.1.2/6.1.3', 'ADDITIONAL', NULL, '환경측면·영향평가와 중대성 기준, 준수의무 식별을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '6.1', '6.1.2/6.1.3', 'ADDITIONAL', NULL, '위험요인 파악·리스크평가와 법규 등 기타 요구사항 파악을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '6.1', '6.1.2/6.1.3', 'ADDITIONAL', NULL, '위험평가 기준·수용기준과 SoA(적용성보고서)가 작성돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO50001', '6.1', '6.1', 'ADDITIONAL', NULL, '에너지성과에 영향을 주는 리스크·기회도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '6.1', '6.1', 'ADDITIONAL', NULL, '위해요소와 관련된 예비 리스크도 반영됐는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '6.1', '4.5/6.1', 'ADDITIONAL', NULL, '부패리스크를 정기적으로, 그리고 거래·파트너별로 평가하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '6.1', '4.6/6.1', 'ADDITIONAL', NULL, '준법리스크를 식별·분석·평가하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22301', '6.1', '6.1', 'ADDITIONAL', NULL, '사업중단 리스크·기회도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '6.1', '6.1.2/6.1.3/6.1.4', 'ADDITIONAL', NULL, 'AI 리스크평가·처리와 함께 AI 영향평가(계획 단계)도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27701', '6.1', '5.2', 'ADDITIONAL', NULL, '개인정보 위험이 ISMS 위험평가에 통합돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '6.1', '6.1', 'ADDITIONAL', NULL, '위조·사기·의심품목(CFSI) 리스크도 포함됐는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO9001', '6.2', '6.2', 'ADDITIONAL', NULL, '품질목표에 제품 적합성 관련 목표가 포함돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO14001', '6.2', '6.2', 'ADDITIONAL', NULL, '환경목표와 지표가 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '6.2', '6.2', 'ADDITIONAL', NULL, '안전보건목표에 측정·모니터링 지표가 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO50001', '6.2', '6.2', 'ADDITIONAL', NULL, '에너지목표가 EnPI와 연결돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '6.2', '6.2', 'ADDITIONAL', NULL, '정보보안목표가 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '6.2', '6.2', 'ADDITIONAL', NULL, '부패방지목표가 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '6.2', '6.2', 'ADDITIONAL', NULL, '준법목표가 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '6.2', '6.2', 'ADDITIONAL', NULL, 'AI 경영목표가 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO9001', '7.1', '7.1.5/7.1.6', 'ADDITIONAL', NULL, '측정장비 교정·검증 기록과 추적성, 조직의 지식 관리도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '7.1', '7.1', 'ADDITIONAL', NULL, '외부에서 개발된 PRP·위해관리 요소를 검증하고 외주 관리를 하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO50001', '7.1', '7.1', 'ADDITIONAL', NULL, '에너지성과 개선에 필요한 자원이 확보돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '7.1', '7.1', 'ADDITIONAL', NULL, 'AI에 필요한 데이터·컴퓨팅자원·전문인력이 확보돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '7.1', '7.1', 'ADDITIONAL', NULL, '측정 추적성과 검교정 관리가 더 꼼꼼한지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '7.2', '7.2', 'ADDITIONAL', NULL, '위험요인·리스크를 인식할 수 있는 역량이 포함돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '7.2', '7.2', 'ADDITIONAL', NULL, '식품안전팀·CCP 담당자의 역량을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '7.2', '7.2.2', 'ADDITIONAL', NULL, '채용·인사 시 청렴성을 확인하고, 성과보상이 부패를 유인하지 않는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '7.2', '7.2.2', 'ADDITIONAL', NULL, '채용 시 준법 관련 사전 확인(실사)을 하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '7.2', '7.2', 'ADDITIONAL', NULL, 'AI 개발·운영 인력의 전문성을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '7.2', '7.2', 'ADDITIONAL', NULL, '특별공정(용접·비파괴검사 등) 담당자의 자격을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '7.3', '7.3', 'ADDITIONAL', NULL, '위험한 상황에서 작업을 멈추거나 벗어날 권리를 근로자가 알고 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '7.3', '7.3', 'ADDITIONAL', NULL, '신고 의무와 신고 채널, 위반 시 결과를 구성원이 알고 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '7.3', '7.3', 'ADDITIONAL', NULL, '신고 의무와 신고 채널, 위반 시 결과를 구성원이 알고 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '7.3', '7.3', 'ADDITIONAL', NULL, '보안사고를 발견하면 보고해야 한다는 것을 알고 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '7.3', '7.3', 'ADDITIONAL', NULL, '식품안전 위해가 생기면 보고해야 한다는 것을 알고 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '7.3', '7.3', 'ADDITIONAL', NULL, '원자력 안전문화(질문하는 자세 등)를 구성원이 인식하고 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO14001', '7.4', '7.4', 'ADDITIONAL', NULL, '준수의무와 관련된 외부 의사소통을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '7.4', '7.4', 'ADDITIONAL', NULL, '근로자 의견을 듣고 협의하는 채널(도급자 포함)이 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '7.4', '7.4', 'ADDITIONAL', NULL, '공급자·고객·규제기관과 식품안전 관련 소통을 하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '7.4', '7.4/8.9', 'ADDITIONAL', NULL, '신고채널(내부고발)을 알리고, 협력사에도 방침을 전달하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22301', '7.4', '7.4', 'ADDITIONAL', NULL, '사업중단 시 이해관계자에게 알리는 소통·경보 체계가 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '7.5', '7.5', 'ADDITIONAL', NULL, '문서 접근권한과 기밀성이 관리되는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27701', '7.5', '7.5(Annex A)/8.5(Annex B)', 'ADDITIONAL', NULL, '개인정보 처리기록·동의기록이 관리되는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '7.5', '7.5', 'ADDITIONAL', NULL, '로트번호·생산일자로 기록의 추적이 가능한지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '7.5', '7.5', 'ADDITIONAL', NULL, '품질기록을 오래 보관하고 추적할 수 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO9001', '9.1', '9.1.2/9.1.3', 'ADDITIONAL', NULL, '고객만족도 모니터링과 데이터 분석을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO14001', '9.1', '9.1.2', 'ADDITIONAL', NULL, '법규 준수 여부를 정기적으로 평가하고 기록하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '9.1', '9.1.2', 'ADDITIONAL', NULL, '법규 준수 여부를 정기적으로 평가하고 기록하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '9.1', '9.1.2~9.1.5', 'ADDITIONAL', NULL, '준수평가와 함께 준법 관련 피드백·지표·보고·기록을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO50001', '9.1', '9.1.1', 'ADDITIONAL', NULL, 'EnPI와 베이스라인 대비 에너지성과를 분석하고, 측정 데이터가 믿을 만한지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '9.1', '9.1', 'ADDITIONAL', NULL, 'PRP·HACCP 계획 모니터링 결과를 분석·검증하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22301', '9.1', '9.1', 'ADDITIONAL', NULL, '사업연속성 대응 능력과 성과를 평가하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '9.1', '9.1', 'ADDITIONAL', NULL, 'AI 시스템 성능과 영향을 모니터링하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '9.2', '9.2', 'ADDITIONAL', NULL, '심사 결과가 컴플라이언스기능·지배기구에 보고되는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '9.2', '9.2', 'ADDITIONAL', NULL, '심사 결과가 컴플라이언스기능·지배기구에 보고되는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '9.2', '9.2', 'ADDITIONAL', NULL, '심사 결과가 시스템 개선에 반영되는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO50001', '9.3', '9.3', 'ADDITIONAL', NULL, 'EnPI·에너지성과 개선 실적을 경영검토에서 다루는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '9.3', '9.3', 'ADDITIONAL', NULL, '지배기구(이사회)도 별도로 검토하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '9.3', '9.3', 'ADDITIONAL', NULL, '근로자 협의·참여 결과를 경영검토에서 다루는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '9.3', '9.3', 'ADDITIONAL', NULL, '비상상황·회수 결과, 외부검증 결과를 경영검토에서 다루는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO42001', '9.3', '9.3', 'ADDITIONAL', NULL, 'AI 영향평가 결과와 규제 변화를 경영검토에서 다루는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '9.3', '9.3', 'ADDITIONAL', NULL, '지배기구 보고가 경영검토에 포함돼 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '10.1', '10.1', 'RENUMBERED', NULL, '27001은 10.1이 \\'지속적개선\\'입니다. 9001의 10.3과 같은 내용이니 헷갈리지 마세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22301', '10.1', '10.1', 'RENUMBERED', NULL, '22301은 10.1이 \\'지속적개선\\'입니다. 9001의 10.3과 같은 내용이니 헷갈리지 마세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '10.1', '10.1', 'RENUMBERED', NULL, '37301은 10.1이 \\'지속적개선\\', 10.2가 \\'부적합 및 시정조치\\'입니다. 9001과 순서가 반대이니 주의하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '10.1', '10.1', 'ADDITIONAL', NULL, '사고가 나기 전에 미리 하는 예방적 개선활동도 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '10.2', '10.2', 'ADDITIONAL', NULL, '사고(Incident) 조사 절차, 근로자 참여, 위험성평가 갱신을 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22000', '10.2', '10.2', 'ADDITIONAL', NULL, '회수·리콜을 실제로 하고 모의훈련 기록이 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37001', '10.2', '8.8~8.10', 'ADDITIONAL', NULL, '부패가 발생하거나 의심될 때 조사·제재·통제개선이 이뤄지는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO19443', '10.2', '10.2', 'ADDITIONAL', NULL, '부적합품을 고객에게 알리고, 위조품(CFSI) 발견 시 조치하는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '10.2', '10.2', 'RENUMBERED', NULL, '27001은 10.2가 \\'부적합 및 시정조치\\'입니다. 내용은 9001과 같고 번호 순서만 반대입니다.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO50001', '10.3', '10.3', 'ADDITIONAL', NULL, '에너지성과가 실제로 계속 좋아지고 있는지(EnPI 추이) 확인하세요. 이 표준의 핵심 요구사항입니다.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO45001', '10.3', '10.3', 'ADDITIONAL', NULL, '개선 결과를 근로자와 소통하고 참여시키는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO14001', '10.3', '10.3', 'ADDITIONAL', NULL, '환경성과가 실제로 개선되고 있는지 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO37301', '10.3', '10.1', 'RENUMBERED', NULL, '37301에는 10.3이 없습니다. 10.1(지속적개선)에서 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO27001', '10.3', '10.1', 'RENUMBERED', NULL, '27001에는 10.3이 없습니다. 10.1(지속적개선)에서 확인하세요.');
INSERT INTO standard_clause_map (standard_code, hls_code, actual_clause_no, status, integrated_into_hls_code, guide_note) VALUES ('ISO22301', '10.3', '10.1', 'RENUMBERED', NULL, '22301에는 10.3이 없습니다. 10.1(지속적개선)에서 확인하세요.');
-- KPI_MASTER → audit_kpi_master (NOT esg kpi_master); normalize 8.2~8.10→8.6~8.10
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.1-1', '4.1', 'COMMON', '이슈목록 갱신주기 준수율', 'RATIO', '실제 갱신 완료 횟수 / 계획된 갱신 횟수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.1-2', '4.1', 'COMMON', '이슈-경영목표 연계율', 'RATIO', '경영목표에 반영된 이슈 수 / 전체 식별 이슈 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.1-3', '4.1', 'COMMON', '이슈 재검토 지연 건수', 'COUNT', '계획된 검토일 대비 지연된 이슈 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.2-1', '4.2', 'COMMON', '이해관계자 요구사항 최신화 주기 준수율', 'RATIO', '기한 내 갱신 완료 건수 / 전체 갱신 대상 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.2-2', '4.2', 'COMMON', '준수의무 위반·이탈 건수', 'COUNT', '준수의무 목록 대비 실제 위반 적발 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.2-3', '4.2', 'COMMON', '요구사항 변경 반영 소요일수', 'PERIOD', '요구사항 변경 인지일 ~ 시스템 반영 완료일', '일');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.3-1', '4.3', 'COMMON', '제외조항 정당화 문서화율', 'RATIO', '정당화 근거가 문서화된 제외조항 수 / 전체 제외조항 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.3-2', '4.3', 'COMMON', '범위 문서 개정 건수(사유별)', 'COUNT', '연간 범위문서 개정 횟수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.4-1', '4.4', 'COMMON', '프로세스맵-실제운영 일치율', 'RATIO', '실사 확인된 일치 프로세스 수 / 전체 프로세스 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.4-2', '4.4', 'COMMON', '프로세스 오너 지정율', 'RATIO', '오너 지정 완료 프로세스 수 / 전체 프로세스 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.4-3', '4.4', 'COMMON', '프로세스 성과지표 미달 건수', 'COUNT', '목표 미달로 판정된 프로세스 성과지표 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K5.1-1', '5.1', 'COMMON', '경영검토 자원배정 이행률', 'RATIO', '실제 배정 완료 자원항목 수 / 경영검토 결정 자원항목 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K5.1-2', '5.1', 'COMMON', '리더십 관련 시정조치 재발 건수', 'COUNT', '동일 리더십 이슈로 재발한 시정조치 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K5.2-1', '5.2', 'COMMON', '방침 인지도', 'RATIO', '인터뷰·설문 정답 인원 수 / 응답 전체 인원 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K5.2-2', '5.2', 'COMMON', '방침 개정 후 재교육 완료율', 'RATIO', '재교육 이수 인원 수 / 대상 인원 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K5.3-1', '5.3', 'COMMON', 'R&R 문서 최신화율', 'RATIO', '최신 조직도/직무기술서 보유 부서 수 / 전체 부서 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K5.3-2', '5.3', 'COMMON', '경영검토 보고 누락 건수', 'COUNT', '계획된 보고 대비 누락된 보고 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.1-1', '6.1', 'COMMON', '리스크 조치 완료율', 'RATIO', '완료된 리스크 대응조치 수 / 식별된 전체 리스크 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.1-2', '6.1', 'COMMON', '리스크 재평가 주기 준수율', 'RATIO', '기한 내 재평가 완료 건수 / 계획된 재평가 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.1-3', '6.1', 'COMMON', '수용기준 초과 잔여리스크 건수', 'COUNT', '처리 후에도 수용기준을 초과하는 리스크 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.2-1', '6.2', 'COMMON', '목표 달성률', 'RATIO', '실적치 / 목표치 × 100 (지표별 산정)', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.2-2', '6.2', 'COMMON', '목표 마일스톤 지연 건수', 'COUNT', '계획 대비 지연된 마일스톤 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.3-1', '6.3', 'COMMON', '계획 외(사후승인) 변경 발생 건수', 'COUNT', '사전계획 없이 사후 승인된 변경 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.3-2', '6.3', 'COMMON', '변경관리 절차 준수율', 'RATIO', '절차 준수 확인된 변경 건수 / 전체 변경 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.3-3', '6.3', 'ISO50001', '에너지검토 갱신주기 준수율', 'RATIO', '기한 내 에너지검토 완료 횟수 / 계획된 횟수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.1-1', '7.1', 'COMMON', '설비 예방정비 계획 준수율', 'RATIO', '계획대로 실시된 정비 건수 / 계획된 정비 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.1-2', '7.1', 'COMMON', '자원부족으로 인한 목표미달 건수', 'COUNT', '자원부족이 원인으로 확인된 목표미달 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.2-1', '7.2', 'COMMON', '역량기준 충족률', 'RATIO', '역량기준을 충족한 인원 수 / 대상 인원 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.2-2', '7.2', 'COMMON', '교육계획 이수율', 'RATIO', '이수 완료 인원 수 / 계획 대상 인원 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.2-3', '7.2', 'COMMON', '교육 효과성 평가 미실시 건수', 'COUNT', '효과성 평가가 누락된 교육과정 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.3-1', '7.3', 'COMMON', '인식도 조사 정답률', 'RATIO', '정답 응답 수 / 전체 응답 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.3-2', '7.3', 'COMMON', '인식교육 미이수 인원 비율', 'RATIO', '미이수 인원 수 / 대상 인원 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.4-1', '7.4', 'COMMON', '소통계획 실행률', 'RATIO', '실행 완료된 소통활동 수 / 계획된 소통활동 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.4-2', '7.4', 'COMMON', '외부 문의·민원 응대 기한 준수율', 'RATIO', '기한 내 응대 완료 건수 / 전체 접수 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.5-1', '7.5', 'COMMON', '문서 개정 지연 건수', 'COUNT', '계획된 개정일 대비 지연 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.5-2', '7.5', 'COMMON', '구버전 사용 적발 건수', 'COUNT', '현장 점검 시 구버전 문서 사용 적발 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-1', '8.1', 'COMMON', '운용기준 부적합 발생 건수', 'COUNT', '운용기준 미준수로 발생한 부적합 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-2', '8.1', 'COMMON', '외주업체 관리기준 미충족 건수', 'COUNT', '평가기준 미달 외주업체 수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.x-1', '8.6~8.10', 'COMMON', '핵심프로세스 계획 대비 실행률', 'RATIO', '실행 완료 항목 수 / 계획 항목 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.x-2', '8.6~8.10', 'COMMON', '프로세스 결과 부적합·이탈 건수', 'COUNT', '표준별 핵심 프로세스에서 발생한 부적합 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.x-3', '8.6~8.10', 'ISO50001', 'EnPI 목표 대비 달성률', 'RATIO', '실측 EnPI 값 / 목표 EnPI 값 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.x-4', '8.6~8.10', 'ISO22000', 'HACCP 검증(CCP) 이탈 건수', 'COUNT', 'CCP 관리기준 이탈 발생 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.x-5', '8.6~8.10', 'ISO27001', 'Annex A 통제 이행률(SoA)', 'RATIO', '이행 완료 통제 수 / SoA상 적용대상 통제 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.x-6', '8.6~8.10', 'ISO22301', 'BC 연습(Exercise) 계획 이행률', 'RATIO', '실시된 연습 횟수 / 연간계획 연습 횟수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.x-7', '8.6~8.10', 'ISO37001', '부패의심 신고 처리기한 준수율', 'RATIO', '기한 내 처리 완료 건수 / 전체 신고 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.x-8', '8.6~8.10', 'ISO42001', 'AI 영향평가 실시율', 'RATIO', '영향평가 완료 AI시스템 수 / 대상 AI시스템 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.x-10', '8.6~8.10', 'ISO19443', 'CFSI(위조·의심품목) 발견 건수', 'COUNT', '공급망 내 위조·의심품목 적발 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K9.1-1', '9.1', 'COMMON', '모니터링 계획 이행률', 'RATIO', '실시 완료 모니터링 건수 / 계획된 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K9.1-2', '9.1', 'COMMON', '측정장비 교정 유효기간 준수율', 'RATIO', '유효기간 내 장비 수 / 전체 대상 장비 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K9.1-3', '9.1', 'COMMON', '데이터분석 결과의 개선조치 반영률', 'RATIO', '개선조치로 이어진 분석건수 / 전체 분석건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K9.2-1', '9.2', 'COMMON', '연간 내부심사 계획 이행률', 'RATIO', '실시 완료 심사 수 / 연간계획 심사 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K9.2-2', '9.2', 'COMMON', '심사 지적사항 시정조치 완료율', 'RATIO', '완료된 시정조치 수 / 전체 지적사항 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K9.2-3', '9.2', 'COMMON', '시정조치 기한 준수율', 'RATIO', '기한 내 완료 건수 / 전체 시정조치 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K9.3-1', '9.3', 'COMMON', '경영검토 후속조치 완료율', 'RATIO', '완료된 후속조치 수 / 결정된 후속조치 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K9.3-2', '9.3', 'COMMON', '경영검토 개최주기 준수여부', 'RATIO', '계획대비 실제 개최 횟수 / 계획 개최 횟수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K10.1-1', '10.1', 'COMMON', '개선 제안-실행 전환율', 'RATIO', '실행 완료 제안 수 / 접수된 개선제안 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K10.1-2', '10.1', 'ISO45001', '예방적 개선활동 실시 건수(사고발생 전)', 'COUNT', '사고 발생 전 선제적으로 실시한 개선활동 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K10.2-1', '10.2', 'COMMON', '부적합 재발률', 'RATIO', '동일원인 재발 건수 / 전체 부적합 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K10.2-2', '10.2', 'COMMON', '시정조치 기한 준수율', 'RATIO', '기한 내 완료 건수 / 전체 시정조치 건수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K10.2-3', '10.2', 'COMMON', '장기 미종결(Open) 건수', 'COUNT', '발행 후 90일 이상 미종결 상태인 시정조치 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K10.3-1', '10.3', 'COMMON', '핵심 KPI 연도별 개선추이', 'TREND', '당해연도 실적 대비 전년동기 실적 비교(증감률)', '% (전년比)');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K10.3-2', '10.3', 'COMMON', '경영검토 개선권고 이행률', 'RATIO', '이행 완료 권고사항 수 / 전체 권고사항 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K10.3-3', '10.3', 'ISO50001', 'EnPI 연간 개선추이', 'TREND', '당해연도 EnPI 값 대비 기준연도(EnB) 값 비교(개선율)', '% (EnB比)');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K4.2-4', '4.2', 'COMMON', '준수의무(법규) 위반 건수', 'COUNT', '실제 관련 법규/규제 위반 적발 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.1-3', '7.1', 'COMMON', '설비 예방보전(정비) 계획 준수율', 'RATIO', '실제 정비 완료 설비 수 / 계획 설비 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-3', '8.1', 'ISO9001', '공정 부적합률(불량률)', 'RATIO', '부적합 수량 / 총 생산 수량 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-4', '8.1', 'ISO9001', '고객 불만(Claim) 발생 건수', 'COUNT', '납품 후 접수된 고객 클레임 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.4-2', '8.4', 'ISO9001', '공급업체(협력사) 정기평가 달성률', 'RATIO', '평가 기준점수 이상 협력사 수 / 전체 평가 협력사 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-5', '8.1', 'ISO14001', '배출허용기준 대비 준수율', 'RATIO', '법적 기준 이내 배출 측정 횟수 / 전체 측정 횟수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-6', '8.1', 'ISO14001', '폐기물 재활용률', 'RATIO', '재활용 폐기물량 / 전체 발생 폐기물량 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.2-2', '8.2', 'ISO14001', '비상대응 훈련 실시율', 'RATIO', '실제 실시한 비상훈련 횟수 / 연간 계획 횟수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.1-4', '6.1', 'ISO45001', '도급/협력사 위험성평가 실시율', 'RATIO', '위험성평가 완료 협력사 수 / 전체 입점 협력사 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-7', '8.1', 'ISO45001', '도수율(Frequency Rate)', 'RATIO', '재해건수 / 총 근로시간수 × 1,000,000', '건/백만시간');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-8', '8.1', 'ISO45001', '강도율(Severity Rate)', 'RATIO', '근로손실일수 / 총 근로시간수 × 1,000', '일/천시간');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-9', '8.1', 'ISO45001', '아차사고(Near Miss) 발굴 건수', 'COUNT', '현장 제출·접수된 아차사고 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K6.3-4', '6.3', 'ISO50001', '에너지 원단위 개선율', 'RATIO', '(전년도 원단위 - 금년도 원단위) / 전년도 원단위 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-10', '8.1', 'ISO22000', 'CCP 한계기준 이탈 건수', 'COUNT', '모니터링 중 CCP 한계기준 초과·미달 발생 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-12', '8.1', 'ISO27001', '보안 사고(Incidents) 발생 건수', 'COUNT', '정보보안 침해 및 유출 사고 발생 건수', '건');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K7.2-4', '7.2', 'ISO27001', '임직원 보안교육 이수율', 'RATIO', '보안교육 이수 인원 / 전체 대상 인원 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-13', '8.1', 'ISO37001', '고위험 직무/협력사 실사(Due Diligence) 이행률', 'RATIO', '실사 완료 대상 수 / 전체 고위험 대상 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.2-3', '8.2', 'ISO37001', '부패방지 서약서 체결률', 'RATIO', '서약서 제출 인원 및 협력사 수 / 전체 대상 수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-14', '8.1', 'ISO22301', 'RTO(복구목표시간) 달성 모의훈련 성공률', 'RATIO', 'RTO 내 복구 성공 훈련 횟수 / 전체 복구 훈련 횟수 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-15', '8.1', 'ISO42001', 'AI 학습데이터 편향성/오류 검증률', 'RATIO', '검증 완료 데이터 세트 / 전체 사용 데이터 세트 × 100', '%');
INSERT INTO audit_kpi_master (kpi_id, hls_code, standard_code, kpi_name, kpi_type, formula, unit) VALUES ('K8.1-16', '8.1', 'ISO19443', 'CFSI(위조/의심품목) 적발 건수', 'COUNT', '입고 검사 및 품질감사 중 적발된 CFSI 건수', '건');
COMMIT;
-- counts expected: PG=8 STD=12 HLS=27 MAP_PG_HLS=22 PROC=48 CLAUSE=131 KPI=84
